### PR TITLE
Add Link Bangle and Gotterdammerung for Ff7Remake.

### PR DESCRIPTION
**Pull request by LAX007**

### CODE REVIEW

**Comment by Xeeynamo** [comment]
The Götterdämmerung is already listed [here](https://github.com/Xeeynamo/KingdomSaveEditor/blob/master/resources/ff7r-meta-items.yml#L1086), while Link Bangle is registered as [Chain Bangle](https://github.com/Xeeynamo/KingdomSaveEditor/blob/master/resources/ff7r-meta-items.yml#L936). Those two items are already available in the save editor. Are they not showing up on your side?

**Comment by LAX007** [comment]
Yes, I was using 15.5 version release to edit pc save, and some items including those two are listed unknown, as my picture shows.
image
I only added thoes two because they are the most powerful, and it worked for me.

**Comment by Xeeynamo** [comment]
> Yes, I was using 15.5 version release to edit pc save, and some items including those two are listed unknown, as my picture shows. image I only added thoes two because they are the most powerful, and it worked for me. I also attached my save in case you need to investigate the reason. [ff7remake001.zip](https://github.com/Xeeynamo/KingdomSaveEditor/files/8196656/ff7remake001.zip)

Interesting. This is not supposed to happen. Do you have Visual Studio? If yes, can you place a breakpoint [here](https://github.com/Xeeynamo/KingdomSaveEditor/blob/master/KHSave.SaveEditor.Ff7Remake/Data/ItemsPreset.cs#L134)? It is supposed to download the new IDs.

**Comment by LAX007** [comment]
The cause seems to be my network issue. After setting proxy, the item list can be successfully loaded from url, and you may close my PR now. But I still wonder why keep the item list online instead of in a local file?

**Pull request closed without merging**
