### PR TITLE
TALESIOFIFREAK's DLC updates w/ fixes

### PR DESCRIPTION
**Pull request by Mirrorman95**
I saw all of TALESIOFIFREAK's recent pull requests and added them to my own local repository, but I also made some corrections to them as well, so I figured I'd post it all as one big pull request. I hope he isn't  at all offended that I'm doing this, because most of this update is his work and he did make most of the corrections I suggested in his own pull requests. But his DLC armor list still looks a little out of order and he didn't standardize the preceding tabs like I did, so I'm posting this here. I can edit this request or take it down if anyone thinks I messed up.

### CODE REVIEW

**Comment by TALESIOFIFREAK** [comment]
i have no problem with it

**Comment by Mirrorman95** [comment]
> i have no problem with it

Thanks.

**Comment by Xeeynamo** [comment]
I appreciate a lot your effort @Mirrorman95 and thank you so much to have take some time to review his changes :)

I already accepted some changes, refused one and put in pending another. I liked the idea to have different pull requests for each change, since they are easier to review.

What do you think?

**Comment by Mirrorman95** [comment]
> I appreciate a lot your effort @Mirrorman95 and thank you so much to have take some time to review his changes :)
> 
> I already accepted some changes, refused one and put in pending another. I liked the idea to have different pull requests for each change, since they are easier to review.
> 
> What do you think?

I mean, I guess I could do things like that moving forward, but I don't know how to resolve the conflicts with this particular pull request. All I can say is that I believe my versions of the files are slightly more accurate. The major functional improvement my version has is that in my ArmorType and InventoryType Power Weight, Magic Weight, and Master Belt are mapped to the correct item numbers, while in TALES's they're not. This conclusion is based on my testing both versions of the editor on the save file submitted by Kidel in Issue #13.

**Comment by Xeeynamo** [comment]
@Mirrorman95 I double-checked and compared your changes once again and I believe that your change is slightly more correct. I can not currently test those values, but I put the trust on you guys for the correct change.

I also solved the conflicts that GitHub was complaining about. Most of them are just formatting issues. I am using Visual Studio 2019, but I believe that you are using a different IDE that does have different formatting options. That's not important though, everything should be fine now ;-)

**Comment by Mirrorman95** [comment]
> @Mirrorman95 I double-checked and compared your changes once again and I believe that your change is slightly more correct. I can not currently test those values, but I put the trust on you guys for the correct change.
> 
> I also solved the conflicts that GitHub was complaining about. Most of them are just formatting issues. I am using Visual Studio 2019, but I believe that you are using a different IDE that does have different formatting options. That's not important though, everything should be fine now ;-)

@Xeeynamo I'm also using MS Visual Studio 2019, but I occasionally edit the files in Notepad++. Is there anything I still need to do with this on my end?

**Comment by Xeeynamo** [comment]
No it is fine. I think the only difference between our two set-ups is that I use spaces and you use tabs lol. Not a big deal

**Pull request merged**
