### PR TITLE
BBSFM save editing

### PR DESCRIPTION
**Pull request by Rikux3**
This PR allows the following edits
- System (Difficulty, Room mod)
- Character (EXP, Level, HP, Weapon etc.)
- Command List
- Decks

There's an bug involving editing a command in the Command List that not displays properly in the Deck Tab. [GIF showcasing that bug.](https://user-images.githubusercontent.com/29046361/82757654-265cb100-9de2-11ea-8493-408fb98f798b.gif)

I've started mapping out the class for the european savefile, but it seems that the IDs for the Commands are different than in FM, so that needs more work.

### CODE REVIEW

**Comment by Xeeynamo** [comment]
Looks very, very good! Having a good Birth By Sleep editor is something I really wanted to see since a very long time. Thank you to bring it to life :)

I am noticing two failing tests though: In KhBbsTests.cs:96 is not writing back the save correctly, but I can see a typo where you were deserializing the save as Final Mix, but it was an european one.
The second is at line 86, where it's expecting FlameSalvo but it gets PaybackRaid instead. Is PaybackRaid the expected command or there is some kind of compatibility problem with the EU version?

For the Character tab, I suggest to wrap it in a ScrollView, since reducing the size of the window would hide some elements.

Finally I would suggest to hide the unknown fields from Character too when the editor is not in Advanced Mode.

As the GIF related to the bug, I know exactly what is happening: you are creating two list of view models for both Command and Deck tabs. What I came up with to fix this bug for other games is to create the CommandViewModel object, then pass it as a parameter to DecksViewModel. The DeckView would use the CommandViewModel's item list and it will detect the changes made from the other tab.

---

That said, apart from the failing tests, let me know what you intend to fix before merging this pull request!

**Comment by Rikux3** [comment]
Thanks for the feedback. I'm going to fix the points you've mentioned as they all make sense to me.

> Is PaybackRaid the expected command or there is some kind of compatibility problem with the EU version?

It seems that the Command IDs don't line up between non-FM and FM versions. For now i'm going to remove the `TestRead` Test for the EU save.

> As the GIF related to the bug, I know exactly what is happening: you are creating two list of view models for both Command and Deck tabs. What I came up with to fix this bug for other games is to create the CommandViewModel object, then pass it as a parameter to DecksViewModel. The DeckView would use the CommandViewModel's item list and it will detect the changes made from the other tab.

Could you name in which class you've did that?

**Comment by Xeeynamo** [comment]
> Could you name in which class you've did that?

FF7RMainViewModel.cs at line 61 I create the ViewModel and at 63 I pass it as a parameter. It will end up in CharacterEntryModel.cs  at line 51 and used as a list when binded to a control :)

**Comment by Rikux3** [comment]
This should fix the previous points.

**Comment by Xeeynamo** [comment]
Looks gorgeous. Merged!

**Pull request merged**
