### PR TITLE
Basic Kingdom Hearts Dream Drop Distance support

### PR DESCRIPTION
**Pull request by Delta-473**
This PR adds basic editing functionality for Kingdom Hearts DDD.

Lib khDDD:
- [x] Worlds
   - [ ] Room names
- [x] Dream Eaters (Only some stats)
- [ ] Equipment:
   - [ ] Abilities
   - [ ] Items
   - [x] Keyblades

GUI:
 - [x] World and room editing
 - [x] Dream Eaters (some stats)
 - [ ] Character editing:
   - [x] Selected keyblade
   - [ ] Abilities
   - [ ] Inventory

Tests:
No test code is included in this PR

### CODE REVIEW

**Comment by Delta-473** [comment]
There is one bug atm where changes you bring to the character tab don't get saved.

**Comment by Xeeynamo** [comment]
Hi @Delta-473 , could you add some unit tests in the same way it's done for the other games? In particular it would be good to have the test `TestWriteBackTheSameExactFile` like it's done here: https://github.com/Xeeynamo/KH3SaveEditor/blob/master/KHSave.Tests/Kh1Tests.cs#L51

**Comment by Delta-473** [comment]
@Xeeynamo added unit test with tests for everything except the difficulty as it's the "wrong" difficulty setting.

**Comment by Xeeynamo** [comment]
Thank you for your contribution 😄  👍

**Pull request merged**
