### PR TITLE
Support for save archives

### PR DESCRIPTION
**Pull request by Rikux3**
This PR aims to add support for PS2 save archives and .PSV files from PS3. I'd also like to support MAX save files, but those are compressed with LZARI, which i couldn't get running on C#.

Currently supports: CBS, PSU, PSV

### CODE REVIEW

**Comment by Rikux3** [comment]
I have a proposal: Would it make sense to implement a "File -> Open Archive" command to differentiate between "pure" saves and archives?

**Comment by Xeeynamo** [comment]
> I have a proposal: Would it make sense to implement a "File -> Open Archive" command to differentiate between "pure" saves and archives?

I think it is simpler to keep everything under the menu "File -> Open" as it would universally work with everything. Is there another reason or any difficulty with your PR that made you coming up with this suggestion? I would like to explore this scenario of yours more.

**Comment by Rikux3** [comment]
I've come with that idea by looking at the last days of people asking questions on how to import a save. But after sleeping a night about it I think my proposal would cause even more confusion on the end user, even when having a user guide (which will come in my next PR)

**Comment by Rikux3** [comment]
Marking this as reviewable. I haven't implemented a `Write` function for the save archives as it was my intention to only let the user export saves (mostly for use on PC)

**Comment by ghost** [comment]
when is the kingdom hearts 3 save editor gonna be ready for the pc version

**Review by Xeeynamo — APPROVED** [review]

**Comment by Xeeynamo** [comment]
> when is the kingdom hearts 3 save editor gonna be ready for the pc version

Never. Stop asking.

**Comment by ghost** [comment]
i thought you wanted to add support for kingdom hearts 3 on pc for the save editor once you cracked it

**Comment by Rikux3** [comment]
Stop being annoying. He gave you an answer.

**Comment by ghost** [comment]
how am i spose to get all gummiship blueprints then for kh3

**Pull request merged**
